### ISSUE TITLE
Recovery can't be flashed via fastboot

### ISSUE THREAD

**Issue by l33tnoob** [Al3XKOoL/WR2-Kernel#1]
need add fb_download flag to recovery partition in /mediatek/build/tools/ptgen/MT6582/partition_table_MT6582.xls (emmc_user list)

**Comment by Al3XKOoL** [comment]
This only applies to the table?
We are using 6mb partitions for recovery and bootimg.

emmc_user partitioned 16mb to bootimg and recovery?

Thanks!!

**Comment by Al3XKOoL** [comment]
Flag added. Check now.
